# Dictionary mapping lowercase brand names to their proper capitalization
# Used for text correction and brand name standardization
brand_names = {
    "airbnb": "Airbnb",
    "google": "Google",
    "apple": "Apple",
    "microsoft": "Microsoft",
    "facebook": "Facebook",
    "amazon": "Amazon",
    "uber": "Uber",
    "lyft": "Lyft",
    "netflix": "Netflix",
    "spotify": "Spotify",
    "instagram": "Instagram",
    "twitter": "Twitter",
    "linkedin": "LinkedIn",
    "youtube": "YouTube",
    "medallia": "Medallia",
    "android": "Android",
    "iphone": "iPhone",
    "ios": "iOS",
    "windows": "Windows",
    "chrome": "Chrome",
    "safari": "Safari",
    "firefox": "Firefox",
    "tesla": "Tesla",
    "spacex": "SpaceX",
    "samsung": "Samsung",
    "sony": "Sony",
    "nvidia": "NVIDIA",
    "intel": "Intel",
    "amd": "AMD",
    "ibm": "IBM",
    "oracle": "Oracle",
    "adobe": "Adobe",
    "salesforce": "Salesforce",
    "slack": "Slack",
    "zoom": "Zoom",
    "tiktok": "TikTok",
    "pinterest": "Pinterest",
    "reddit": "Reddit",
    "whatsapp": "WhatsApp",
    "snapchat": "Snapchat",
    "discord": "Discord",
    "twitch": "Twitch",
    "paypal": "PayPal",
    "venmo": "Venmo",
    "dropbox": "Dropbox",
    "ebay": "eBay",
    "aliexpress": "AliExpress",
    "walmart": "Walmart",
    "target": "Target",
    "starbucks": "Starbucks",
    "nike": "Nike",
    "adidas": "Adidas",
    "playstation": "PlayStation",
    "xbox": "Xbox",
    "nintendo": "Nintendo",
    "dell": "Dell",
    "hp": "HP",
    "lenovo": "Lenovo",
    "cisco": "Cisco",
    "qualcomm": "Qualcomm",
    "volkswagen": "Volkswagen",
    "toyota": "Toyota",
    "ford": "Ford",
    "bmw": "BMW",
    "mercedes": "Mercedes",
    "audi": "Audi",
    "disney": "Disney",
    "hbo": "HBO",
    "hulu": "Hulu",
    "peacock": "Peacock",
    "paramount": "Paramount",
    "blizzard": "Blizzard",
    "riot": "Riot Games",
    "epic": "Epic Games",
    "ubuntu": "Ubuntu",
    "fedora": "Fedora",
    "linux": "Linux",
    "git": "Git",
    "github": "GitHub",
    "gitlab": "GitLab",
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "atlassian": "Atlassian",
    "jira": "Jira",
    "trello": "Trello",
    "wordpress": "WordPress",
    "shopify": "Shopify",
    "wix": "Wix",
    "squarespace": "Squarespace",
    "wechat": "WeChat",
    "alibaba": "Alibaba",
    "tencent": "Tencent",
    "huawei": "Huawei",
    "xiaomi": "Xiaomi",
    "oneplus": "OnePlus",
    "oppo": "OPPO",
    "vivo": "Vivo",
    "realme": "Realme",
    "lg": "LG",
    "panasonic": "Panasonic",
    "philips": "Philips",
    "bosch": "Bosch",
    "siemens": "Siemens",
    "ge": "GE",
    "general electric": "General Electric",
    "boeing": "Boeing",
    "airbus": "Airbus",
    "lockheed": "Lockheed Martin",
    "nasa": "NASA",
    "spacex": "SpaceX",
    "blue origin": "Blue Origin",
    "virgin galactic": "Virgin Galactic",
    "mastercard": "Mastercard",
    "visa": "Visa",
    "american express": "American Express",
    "amex": "Amex",
    "discover": "Discover",
    "capital one": "Capital One",
    "chase": "Chase",
    "bank of america": "Bank of America",
    "wells fargo": "Wells Fargo",
    "citi": "Citi",
    "goldman sachs": "Goldman Sachs",
    "morgan stanley": "Morgan Stanley",
    "blackrock": "BlackRock",
    "fidelity": "Fidelity",
    "schwab": "Charles Schwab",
    "robinhood": "Robinhood",
    "coinbase": "Coinbase",
    "binance": "Binance",
    "bitcoin": "Bitcoin",
    "ethereum": "Ethereum",
    "solana": "Solana",
    "ripple": "Ripple",
    "cardano": "Cardano",
    "polygon": "Polygon",
    "opensea": "OpenSea",
    "nft": "NFT",
    "meta": "Meta",
    "oculus": "Oculus",
    "valve": "Valve",
    "steam": "Steam",
    "electronic arts": "Electronic Arts",
    "ea": "EA",
    "activision": "Activision",
    "ubisoft": "Ubisoft",
    "take two": "Take-Two Interactive",
    "rockstar": "Rockstar Games",
    "square enix": "Square Enix",
    "bandai namco": "Bandai Namco",
    "sega": "Sega",
    "capcom": "Capcom",
    "konami": "Konami",
    "warner bros": "Warner Bros.",
    "universal": "Universal",
    "sony pictures": "Sony Pictures",
    "paramount": "Paramount",
    "netflix": "Netflix",
    "spotify": "Spotify",
    "soundcloud": "SoundCloud",
    "bandcamp": "Bandcamp",
    "tidal": "Tidal",
    "deezer": "Deezer",
    "pandora": "Pandora",
    "shazam": "Shazam",
    "vimeo": "Vimeo",
    "dailymotion": "Dailymotion",
    "imdb": "IMDb",
    "rottentomatoes": "Rotten Tomatoes",
    "fandango": "Fandango",
    "booking": "Booking.com",
    "expedia": "Expedia",
    "tripadvisor": "TripAdvisor",
    "trivago": "Trivago",
    "zillow": "Zillow",
    "realtor": "Realtor.com",
    "redfin": "Redfin",
    "craigslist": "Craigslist",
    "etsy": "Etsy",
    "groupon": "Groupon",
    "kickstarter": "Kickstarter",
    "indiegogo": "Indiegogo",
    "patreon": "Patreon",
    "asana": "Asana",
    "basecamp": "Basecamp",
    "notion": "Notion",
    "evernote": "Evernote",
    "monday": "Monday.com",
    "airtable": "Airtable",
    "figma": "Figma",
    "sketch": "Sketch",
    "invision": "InVision",
    "canva": "Canva",
    "adobe xd": "Adobe XD",
    "zoho": "Zoho",
    "mailchimp": "Mailchimp",
    "hubspot": "HubSpot",
    "semrush": "SEMrush",
    "moz": "Moz",
    "ahrefs": "Ahrefs",
    "hootsuite": "Hootsuite",
    "buffer": "Buffer",
    "sprout social": "Sprout Social",
    "zendesk": "Zendesk",
    "freshdesk": "Freshdesk",
    "intercom": "Intercom",
    "help scout": "Help Scout",
    "square": "Square",
    "stripe": "Stripe",
    "quickbooks": "QuickBooks",
    "xero": "Xero",
    "wave": "Wave",
    "mint": "Mint",
    "credit karma": "Credit Karma",
    "turbo tax": "TurboTax",
    "hr block": "H&R Block",
    "roku": "Roku",
    "fire tv": "Fire TV",
    "chromecast": "Chromecast",
    "logitech": "Logitech",
    "razer": "Razer",
    "corsair": "Corsair",
    "hyperx": "HyperX",
    "steelseries": "SteelSeries",
    "asus": "ASUS",
    "acer": "Acer",
    "msi": "MSI",
    "nokia": "Nokia",
    "blackberry": "BlackBerry",
    "motorola": "Motorola",
    "htc": "HTC",
    "zte": "ZTE",
    "blackview": "Blackview",
    "doogee": "Doogee",
    "rolex": "Rolex",
    "omega": "Omega",
    "casio": "Casio",
    "fossil": "Fossil",
    "garmin": "Garmin",
    "fitbit": "Fitbit",
    "xiaomi": "Xiaomi",
    "gopro": "GoPro",
    "dji": "DJI",
    "nikon": "Nikon",
    "canon": "Canon",
    "sony": "Sony",
    "fujifilm": "Fujifilm",
    "leica": "Leica",
    "polaroid": "Polaroid",
    "kodak": "Kodak",
    "nest": "Nest",
    "ring": "Ring",
    "arlo": "Arlo",
    "simplisafe": "SimpliSafe",
    "adt": "ADT",
    "honeywell": "Honeywell",
    "ecobee": "Ecobee",
    "lifx": "LIFX",
    "philips hue": "Philips Hue",
    "ikea": "IKEA",
    "wayfair": "Wayfair",
    "overstock": "Overstock",
    "houzz": "Houzz",
    "home depot": "Home Depot",
    "lowes": "Lowe's",
    "best buy": "Best Buy",
    "costco": "Costco",
    "sam's club": "Sam's Club",
    "whole foods": "Whole Foods",
    "trader joe's": "Trader Joe's",
    "safeway": "Safeway",
    "kroger": "Kroger",
    "publix": "Publix",
    "aldi": "ALDI",
    "lidl": "Lidl",
    "tesco": "Tesco",
    "sainsbury's": "Sainsbury's",
    "waitrose": "Waitrose",
    "m&s": "M&S",
    "marks and spencer": "Marks & Spencer",
    "unilever": "Unilever",
    "procter & gamble": "Procter & Gamble",
    "pg": "P&G",
    "nestle": "Nestlé",
    "pepsi": "Pepsi",
    "coca cola": "Coca-Cola",
    "coke": "Coke",
    "dr pepper": "Dr Pepper",
    "sprite": "Sprite",
    "fanta": "Fanta",
    "mcdonald's": "McDonald's",
    "burger king": "Burger King",
    "kfc": "KFC",
    "subway": "Subway",
    "domino's": "Domino's",
    "pizza hut": "Pizza Hut",
    "taco bell": "Taco Bell",
    "chipotle": "Chipotle",
    "panera bread": "Panera Bread",
    "dunkin'": "Dunkin'",
    "dunkin donuts": "Dunkin' Donuts",
    "baskin robbins": "Baskin-Robbins",
    "haagen dazs": "Häagen-Dazs",
    "ben & jerry's": "Ben & Jerry's",
    "hershey's": "Hershey's",
    "mars": "Mars",
    "snickers": "Snickers",
    "twix": "Twix",
    "kit kat": "Kit Kat",
    "milky way": "Milky Way",
    "haribo": "Haribo",
    "starburst": "Starburst",
    "skittles": "Skittles",
    "pringles": "Pringles",
    "lays": "Lay's",
    "doritos": "Doritos",
    "cheetos": "Cheetos",
    "ruffles": "Ruffles",
    "frito lay": "Frito-Lay",
    "quaker": "Quaker",
    "kellogg's": "Kellogg's",
    "general mills": "General Mills",
    "kraft": "Kraft",
    "heinz": "Heinz",
    "campbell's": "Campbell's",
    "nabisco": "Nabisco",
    "oreo": "Oreo",
    "ritz": "Ritz",
    "triscuit": "Triscuit",
    "pepsi co": "PepsiCo",
    "red bull": "Red Bull",
    "monster": "Monster",
    "rockstar energy": "Rockstar Energy",
    "bang": "Bang",
    "gatorade": "Gatorade",
    "powerade": "Powerade",
    "vitaminwater": "Vitaminwater",
    "smartwater": "smartwater",
    "evian": "Evian",
    "perrier": "Perrier",
    "san pellegrino": "San Pellegrino",
    "dove": "Dove",
    "axe": "Axe",
    "old spice": "Old Spice",
    "colgate": "Colgate",
    "crest": "Crest",
    "oral b": "Oral-B",
    "sensodyne": "Sensodyne",
    "listerine": "Listerine",
    "tide": "Tide",
    "gain": "Gain",
    "downy": "Downy",
    "bounce": "Bounce",
    "arm & hammer": "Arm & Hammer",
    "clorox": "Clorox",
    "lysol": "Lysol",
    "purell": "Purell",
    "palmer's": "Palmer's",
    "neutrogena": "Neutrogena",
    "olay": "Olay",
    "cerave": "CeraVe",
    "aveeno": "Aveeno",
    "dove men+care": "Dove Men+Care",
    "gillette": "Gillette",
    "schick": "Schick",
    "dollar shave club": "Dollar Shave Club",
    "harry's": "Harry's",
    "revlon": "Revlon",
    "maybelline": "Maybelline",
    "l'oreal": "L'Oréal",
    "covergirl": "CoverGirl",
    "nyx": "NYX",
    "mac": "MAC",
    "estee lauder": "Estée Lauder",
    "clinique": "Clinique",
    "kiehl's": "Kiehl's",
    "the ordinary": "The Ordinary",
    "glossier": "Glossier",
    "fenty beauty": "Fenty Beauty",
    "huda beauty": "Huda Beauty",
    "too faced": "Too Faced",
    "tarte": "Tarte",
    "urban decay": "Urban Decay",
    "anastasia beverly hills": "Anastasia Beverly Hills",
    "nars": "NARS",
    "benefit": "Benefit",
    "sephora": "Sephora",
    "ulta": "Ulta",
    "lush": "Lush",
    "bath & body works": "Bath & Body Works",
    "victoria's secret": "Victoria's Secret",
    "calvin klein": "Calvin Klein",
    "tommy hilfiger": "Tommy Hilfiger",
    "ralph lauren": "Ralph Lauren",
    "levi's": "Levi's",
    "wrangler": "Wrangler",
    "gap": "Gap",
    "old navy": "Old Navy",
    "banana republic": "Banana Republic",
    "h&m": "H&M",
    "zara": "Zara",
    "uniqlo": "Uniqlo",
    "forever 21": "Forever 21",
    "american eagle": "American Eagle",
    "aeropostale": "Aeropostale",
    "hollister": "Hollister",
    "abercrombie & fitch": "Abercrombie & Fitch",
    "lululemon": "Lululemon",
    "under armour": "Under Armour",
    "puma": "Puma",
    "reebok": "Reebok",
    "new balance": "New Balance",
    "converse": "Converse",
    "vans": "Vans",
    "skechers": "Skechers",
    "crocs": "Crocs",
    "ugg": "UGG",
    "timberland": "Timberland",
    "dr martens": "Dr. Martens",
    "clarks": "Clarks",
    "steve madden": "Steve Madden",
    "cole haan": "Cole Haan",
    "jimmy choo": "Jimmy Choo",
    "gucci": "Gucci",
    "louis vuitton": "Louis Vuitton",
    "chanel": "Chanel",
    "dior": "Dior",
    "prada": "Prada",
    "versace": "Versace",
    "armani": "Armani",
    "burberry": "Burberry",
    "hermes": "Hermès",
    "tiffany & co": "Tiffany & Co.",
    "rolex": "Rolex",
    "omega": "Omega",
    "tag heuer": "Tag Heuer",
    "breitling": "Breitling",
    "rolex": "Rolex",
    "cartier": "Cartier",
    "rolex": "Rolex",
    "rolex": "Rolex",
    "rolex": "Rolex",
}

# Dictionary of common contractions that might be incorrectly spelled
# Maps the incorrect form to the correct form with apostrophes
manual_contractions = {
    "itll": "it'll",
    "youll": "you'll",
    "theyll": "they'll",
    "thatll": "that'll",
    "wholl": "who'll",
    "whatll": "what'll",
    "wont": "won't",
    "cant": "can't",
    "shouldnt": "shouldn't",
    "couldnt": "couldn't",
    "wouldnt": "wouldn't",
    "doesnt": "doesn't",
    "didnt": "didn't",
    "hasnt": "hasn't",
    "hadnt": "hadn't",
    "havent": "haven't",
    "isnt": "isn't",
    "arent": "aren't",
    "wasnt": "wasn't",
    "werent": "weren't"
}

# List of contraction patterns used to generate valid contractions
# Each pattern is a tuple of (base_words, ending)
# Used to programmatically generate contractions from base words
patterns = [
    # Future tense ('will' contractions)
    (['i', 'you', 'he', 'she', 'it', 'we', 'they', 'that', 'this', 'who', 'what', 'there'], 'll'),
    # "there'll", "who'll"

    # Present perfect ('have' contractions)
    (['i', 'you', 'he', 'she', 'it', 'we', 'they', 'there'], 've'),  # "there've" (informal)

    # Present continuous ('are' contractions)
    (['you', 'we', 'they', 'there'], 're'),  # "there're" (informal)

    # Modal contractions ('would'/'had'/'should')
    (['i', 'you', 'he', 'she', 'it', 'we', 'they', 'there', 'who', 'what'], 'd'),  # "who'd", "there'd"

    # 'am' contraction
    (['i'], 'm'),  # "I'm"

    # 'is'/'has' contractions
    (['it', 'that', 'this', 'he', 'she', 'there', 'who', 'what', 'where', 'when', 'why', 'how'], 's'),
    # "who's", "where's"

    # Negations
    (['is', 'are', 'was', 'were', 'have', 'has', 'had', 'do', 'does', 'did', 'can', 'could', 'will', 'would', 'should',
      'must', 'might'], 'n\'t'),  # "isn't", "can't", "won't"

    # Informal/regional contractions
    (['you'], 'all'),  # "y'all" (Southern U.S.)
    (['let'], 's'),  # "let's"
    (['o'], 'clock'),  # "o'clock"
    (['ma'], 'am'),  # "ma'am"
]

# List of base words that can form negative contractions with "n't"
# Used to generate negative contractions like "isn't", "don't", etc.
negative_bases = [
    # Standard auxiliaries
    'do', 'does', 'did',
    'is', 'are', 'was', 'were',
    'have', 'has', 'had',
    'will', 'would', 'shall', 'should',
    'can', 'could', 'may', 'might', 'must',

    # Less common but valid
    'need', 'dare', 'ought', 'used',

    # Informal/slang
    'ain',  # For "ain't" (colloquial, covers "am not"/"is not"/"are not"/etc.)
    'shant',  # "shan't" (British for "shall not")
    'mustn',  # "mustn't"
    'daren',  # "daren't" (British)
    'needn',  # "needn't"
]

# List of special contractions that have irregular forms or are not easily generated
# These are added directly to the contractions set
special_contractions = [
    # Standard irregular contractions
    "can't",  # cannot → "can not" is rarely used
    "won't",  # will not (from Old English "wonnot")
    "shan't",  # shall not (British, archaic in US English)

    # Informal/colloquial
    "ain't",  # (am not/is not/are not/has not/have not) - widely used but nonstandard

    # Less common but valid
    "mayn't",  # may not (archaic/rare)
    "needn't",  # need not (common in UK English)
    "daren't",  # dare not (British)

    # Phonetically unique
    "mustn't",  # must not (shortened unusually)
    "mightn't",  # might not (rare but correct)
    "oughtn't",  # ought not (formal/archaic)

    # Regional/older forms
    "usedn't",  # used not (rare, e.g., "He usedn't to smoke")
    "amn't",  # am not (dialectal, e.g., Irish/Southern US: "I amn't sure")

    # Slang/eye dialect
    "couldn't've",  # could not have
    "shouldn't've",  # should not have
    "wouldn't've",  # would not have
]

# Set of common English words used for text processing and validation
# Includes basic vocabulary, common verbs, pronouns, and domain-specific terms
common_words = {
        'the', 'a', 'an', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for', 'of', 'with',
        'by', 'from', 'up', 'about', 'into', 'through', 'during', 'before', 'after',
        'above', 'below', 'between', 'among', 'this', 'that', 'these', 'those', 'i', 'you',
        'he', 'she', 'it', 'we', 'they', 'me', 'him', 'her', 'us', 'them', 'my', 'your',
        'his', 'her', 'its', 'our', 'their', 'mine', 'yours', 'his', 'hers', 'ours',
        'theirs', 'am', 'is', 'are', 'was', 'were', 'being', 'been', 'be', 'have', 'has',
        'had', 'do', 'does', 'did', 'will', 'would', 'should', 'could', 'can', 'may',
        'might', 'must', 'shall', 'should', 'ought', 'need', 'dare', 'used', 'able',
        'going', 'get', 'got', 'make', 'made', 'take', 'took', 'come', 'came', 'go',
        'went', 'see', 'saw', 'know', 'knew', 'think', 'thought', 'say', 'said', 'tell',
        'told', 'ask', 'asked', 'work', 'worked', 'seem', 'seemed', 'feel', 'felt',
        'try', 'tried', 'leave', 'left', 'call', 'called', 'want', 'wanted', 'turn',
        'turned', 'move', 'moved', 'like', 'liked', 'look', 'looked', 'find', 'found',
        'give', 'gave', 'use', 'used', 'tell', 'told', 'become', 'became', 'show',
        'showed', 'hear', 'heard', 'play', 'played', 'run', 'ran', 'walk', 'walked',
        'talk', 'talked', 'sit', 'sat', 'stand', 'stood', 'lose', 'lost', 'pay', 'paid',
        'meet', 'met', 'include', 'included', 'continue', 'continued', 'set', 'put',
        'end', 'ended', 'why', 'what', 'when', 'where', 'who', 'which', 'how', 'all',
        'any', 'some', 'no', 'not', 'only', 'other', 'another', 'such', 'very', 'still',
        'just', 'now', 'even', 'also', 'well', 'back', 'there', 'here', 'where', 'when',
        'why', 'how', 'what', 'which', 'who', 'whom', 'whose', 'few', 'little', 'much',
        'many', 'most', 'more', 'less', 'least', 'several', 'own', 'same', 'different',
        'new', 'old', 'young', 'good', 'bad', 'great', 'small', 'large', 'big', 'little',
        'long', 'short', 'high', 'low', 'right', 'left', 'next', 'last', 'first', 'second',
        'third', 'answer', 'answers', 'question', 'questions', 'minute', 'minutes',
        'experience', 'guest', 'guests', 'travel', 'plan', 'plans', 'help', 'survey',
        'team', 'policy', 'privacy', 'download', 'store', 'play', 'app', 'email',
        'service', 'company', 'customer', 'user', 'account', 'profile', 'settings'

        # Marketing & Advertising
        'buy', 'sale', 'discount', 'offer', 'deal', 'promo', 'promotion', 'limited', 'exclusive',
        'free', 'shipping', 'delivery', 'order', 'purchase', 'price', 'pricing', 'cost', 'value',
        'premium', 'luxury', 'affordable', 'budget', 'save', 'savings', 'bundle', 'discounts',
        'coupon', 'voucher', 'code', 'subscribe', 'subscription', 'trial', 'membership', 'reward',
        'loyalty', 'points', 'bonus', 'gift', 'giveaway', 'contest', 'win', 'winner', 'entry',
        'brand', 'branding', 'campaign', 'ad', 'ads', 'advert', 'advertising', 'sponsored',
        'endorsement', 'influencer', 'content', 'engagement', 'reach', 'impressions', 'clicks',
        'conversion', 'CTR', 'ROI', 'metrics', 'analytics', 'target', 'audience', 'demographic',
        'segment', 'niche', 'trend', 'viral', 'SEO', 'SEM', 'PPC', 'social', 'media', 'platform',
        'organic', 'paid', 'boost', 'optimize', 'optimization', 'landing', 'page', 'CTA', 'button',
        'lead', 'leads', 'funnel', 'sales', 'conversion', 'retention', 'churn', 'customer', 'clients',
        'B2B', 'B2C', 'ecommerce', 'shop', 'store', 'cart', 'checkout', 'payment', 'refund',
        'return', 'warranty', 'guarantee', 'trust', 'reviews', 'ratings', 'testimonials', 'feedback',

        # Compliance & Legal
        'terms', 'conditions', 'privacy', 'policy', 'GDPR', 'CCPA', 'compliance', 'regulation',
        'regulatory', 'legal', 'disclaimer', 'disclosure', 'consent', 'opt-in', 'opt-out',
        'unsubscribe', 'cookie', 'cookies', 'data', 'protection', 'security', 'encryption',
        'breach', 'liability', 'waiver', 'jurisdiction', 'governance', 'audit', 'certification',
        'standard', 'guidelines', 'restrictions', 'prohibited', 'fraud', 'scam', 'anti-spam',
        'copyright', 'trademark', 'patent', 'intellectual', 'property', 'infringement',
        'amendments', 'updates', 'notices', 'agreement', 'contract', 'signature', 'binding',
        'enforceable', 'violation', 'penalty', 'fine', 'sanction', 'arbitration', 'dispute',

        # Digital & Tech
        'app', 'application', 'mobile', 'desktop', 'web', 'browser', 'login', 'signup', 'password',
        'authentication', 'verification', 'OTP', '2FA', 'API', 'integration', 'cloud', 'hosting',
        'server', 'domain', 'SSL', 'firewall', 'malware', 'phishing', 'authentication', 'session',
        'cache', 'cookies', 'tracking', 'pixel', 'algorithm', 'AI', 'machine', 'learning',
        'automation', 'chatbot', 'support', 'ticket', 'helpdesk', 'FAQ', 'documentation', 'onboarding',

        # General Business
        'company', 'business', 'enterprise', 'startup', 'SME', 'LLC', 'inc', 'corp', 'partnership',
        'vendor', 'supplier', 'partner', 'stakeholder', 'investor', 'shareholder', 'board',
        'executive', 'management', 'HR', 'hiring', 'recruitment', 'onboarding', 'training',
        'workplace', 'remote', 'hybrid', 'office', 'culture', 'diversity', 'inclusion', 'ethics',
        'sustainability', 'CSR', 'environmental', 'impact', 'ESG', 'transparency', 'reporting',
        'annual', 'quarterly', 'financial', 'revenue', 'profit', 'loss', 'margin', 'growth',
        'scalability', 'strategy', 'planning', 'forecasting', 'KPIs', 'OKRs', 'metrics',
        'benchmark', 'competitor', 'market', 'research', 'survey', 'poll', 'feedback', 'insights',
        'innovation', 'disruption', 'competitive', 'advantage', 'USP', 'value', 'proposition',
}

# List of regex patterns for text corrections
# Each tuple contains (pattern, replacement)
# Used to fix common OCR and text formatting errors
corrections = [
    # Number + time units (expanded)
    (r'\b(\d+)minutes\b', r'\1 minutes'),
    (r'\b(\d+)seconds\b', r'\1 seconds'),
    (r'\b(\d+)hours\b', r'\1 hours'),
    (r'\b(\d+)days\b', r'\1 days'),
    (r'\b(\d+)weeks\b', r'\1 weeks'),
    (r'\b(\d+)months\b', r'\1 months'),
    (r'\b(\d+)years\b', r'\1 years'),
    (r'\b(\d+)mins\b', r'\1 mins'),  # Abbreviated forms
    (r'\b(\d+)hrs\b', r'\1 hrs'),
    (r'\b(\d+)wks\b', r'\1 wks'),

    # Common word concatenations (marketing/UX focus)
    (r'\byouranswers\b', 'your answers'),
    (r'\byourexperience\b', 'your experience'),
    (r'\byourtravel\b', 'your travel'),
    (r'\byourreservation\b', 'your reservation'),
    (r'\byourhotel\b', 'your hotel'),
    (r'\byourtrip\b', 'your trip'),
    (r'\byourorder\b', 'your order'),
    (r'\byourcart\b', 'your cart'),
    (r'\byouraccount\b', 'your account'),
    (r'\byourprofile\b', 'your profile'),
    (r'\byoursettings\b', 'your settings'),
    (r'\byourdata\b', 'your data'),
    (r'\byourprivacy\b', 'your privacy'),
    (r'\byourchoices\b', 'your choices'),
    (r'\byourpreferences\b', 'your preferences'),

    # Marketing/CTA phrases
    (r'\bclickhere\b', 'click here'),
    (r'\bsignupnow\b', 'sign up now'),
    (r'\bgetstarted\b', 'get started'),
    (r'\blearnmore\b', 'learn more'),
    (r'\bshopnow\b', 'shop now'),
    (r'\bdownloadnow\b', 'download now'),
    (r'\bclaimoffer\b', 'claim offer'),
    (r'\blimitedtime\b', 'limited time'),
    (r'\bexclusiveoffer\b', 'exclusive offer'),
    (r'\bfreeshipping\b', 'free shipping'),
    (r'\bspecialdeal\b', 'special deal'),

    # Compliance/legal terms
    (r'\btermsconditions\b', 'terms conditions'),
    (r'\bprivacypolicy\b', 'privacy policy'),
    (r'\bcookiepolicy\b', 'cookie policy'),
    (r'\buseragreement\b', 'user agreement'),
    (r'\bdataprotection\b', 'data protection'),
    (r'\boptout\b', 'opt out'),
    (r'\boptin\b', 'opt in'),
    (r'\bunsubscribelink\b', 'unsubscribe link'),

    # Common UX/help phrases
    (r'\bmakesure\b', 'make sure'),
    (r'\bthankyou\b', 'thank you'),
    (r'\bpleasecheck\b', 'please check'),
    (r'\bcontactus\b', 'contact us'),
    (r'\bfaqpage\b', 'FAQ page'),
    (r'\bhelppage\b', 'help page'),
    (r'\bsupportteam\b', 'support team'),
    (r'\bpasswordreset\b', 'password reset'),

    # Tech/digital terms
    (r'\bloginpage\b', 'login page'),
    (r'\bsignuppage\b', 'signup page'),
    (r'\bhomepage\b', 'home page'),
    (r'\bcheckoutpage\b', 'checkout page'),
    (r'\bpricingpage\b', 'pricing page'),
    (r'\blandingpage\b', 'landing page'),
]

# Combine all data structures into a single dictionary for export
data = {
    "brand_names": brand_names,
    "patterns": patterns,
    "manual_contractions": manual_contractions,
    "negative_bases": negative_bases,
    "special_contractions": special_contractions,
    "common_words": list(common_words),
    "corrections": corrections,
}

# Print the types of each data structure for debugging
for name, value in data.items():
    print(f"{name}: {type(value)}")

# Import libraries for data serialization
import json

# Save to JSON file for human-readable format
with open('text_processing_data.json', 'w') as f:
    json.dump(data, f, indent=4)

print("JSON file created successfully!")

import pickle

# Save to Pickle file for efficient loading in Python
with open('text_processing_data.pkl', 'wb') as f:
    pickle.dump(data, f)
